package com.focoenglish.mobile;
import android.app.*;import android.os.*;import android.content.*;import android.database.Cursor;import android.net.Uri;import android.provider.OpenableColumns;import android.webkit.*;import android.widget.Toast;import androidx.annotation.Nullable;import androidx.core.content.FileProvider;import java.io.*;import java.nio.charset.StandardCharsets;
public class MainActivity extends Activity{
 private WebView web; private static final int PICK_BACKUP=71,CREATE_BACKUP=72,PICK_PDF=73; private String pendingBackup;
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);web=findViewById(R.id.webview);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setMediaPlaybackRequiresUserGesture(false);web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri u=r.getUrl();if(!u.toString().startsWith("file:///android_asset/")){openExternal(u);return true;}return false;}});web.addJavascriptInterface(new Bridge(),"Android");web.loadUrl("file:///android_asset/index.html");}
 private void openExternal(Uri uri){try{startActivity(new Intent(Intent.ACTION_VIEW,uri));}catch(Exception e){toast("Não foi possível abrir.");}}
 private void toast(String t){runOnUiThread(()->Toast.makeText(this,t,Toast.LENGTH_SHORT).show());}
 public class Bridge{
  @JavascriptInterface public void openUrl(String url){runOnUiThread(()->openExternal(Uri.parse(url)));}
  @JavascriptInterface public void exportBackup(String text){pendingBackup=text;runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"focoenglish_backup_v2.json");startActivityForResult(i,CREATE_BACKUP);});}
  @JavascriptInterface public void chooseBackup(){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_BACKUP);});}
  @JavascriptInterface public void choosePdf(){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/pdf");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_PDF);});}
  @JavascriptInterface public void openPdf(String fileId){runOnUiThread(()->{try{File f=new File(new File(getFilesDir(),"pdfs"),fileId+".pdf");if(!f.exists()){toast("PDF não encontrado.");return;}Uri u=FileProvider.getUriForFile(MainActivity.this,getPackageName()+".provider",f);Intent i=new Intent(Intent.ACTION_VIEW).setDataAndType(u,"application/pdf").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(i);}catch(Exception e){toast("Instala ou ativa um leitor de PDF no telefone.");}});}
 }
 private String displayName(Uri u){String n="documento.pdf";try(Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(i>=0)n=c.getString(i);}}return n;}
 @Override protected void onActivityResult(int req,int result,@Nullable Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();try{if(req==CREATE_BACKUP&&pendingBackup!=null){try(OutputStream o=getContentResolver().openOutputStream(u)){o.write(pendingBackup.getBytes(StandardCharsets.UTF_8));}toast("Backup exportado.");}else if(req==PICK_BACKUP){String t;try(InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream o=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))>0)o.write(b,0,n);t=o.toString("UTF-8");}web.evaluateJavascript("window.importBackup("+org.json.JSONObject.quote(t)+")",null);}else if(req==PICK_PDF){File dir=new File(getFilesDir(),"pdfs");if(!dir.exists())dir.mkdirs();String id=String.valueOf(System.currentTimeMillis());File out=new File(dir,id+".pdf");try(InputStream in=getContentResolver().openInputStream(u);OutputStream os=new FileOutputStream(out)){byte[] b=new byte[8192];int n;while((n=in.read(b))>0)os.write(b,0,n);}String name=displayName(u);web.evaluateJavascript("window.onPdfImported("+org.json.JSONObject.quote(id)+","+org.json.JSONObject.quote(name)+")",null);}}catch(Exception e){toast("Não foi possível concluir a operação.");}}
 @Override public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
}